elasticsearch:
  host: localhost
  port: 9200
  api_key: key
  password: elastic
  id: elastic

spring:
  profiles:
    active: elk


#spring.data.elasticsearch.cluster-nodes=localhost:9200
#spring.data.elasticsearch.cluster-name=my-elasticsearch-cluster