elasticsearch:
  host: localhost
  port: 9200
  schema: http
  apiKey: RVVzYktJNEI2M2RCTGNORUlOeGM6SnFSTTgwV3RRN21ZLTBrN3dHQ1J0dw==
  serverURL: http://localhost:9200
  login:
    password: elastic
    id: elastic
  indecies:
    studentsIndexName: students
    testIndexName: tests

spring:
  profiles:
    active: elk