elasticsearch:
  host: localhost
  port: 9200
  api_key: key
  password: elastic
  id: elastic
  indecies:
    studentsIndexName: students
    testIndexName: tests

spring:
  profiles:
    active: elk